### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by rkrenn**

### CODE REVIEW

**Review by josharmenta — APPROVED** [review]

**Comment by rkrenn** [comment]
@josharmenta @viiliainen 
how to proceed now, you know who can help with your swedish/spanish translations?
it's giant, there are tens of thousands of strings.

we try to contact crowdin folks for advise on how to apply automatic translations for this initial commit. does it make sense?

**Comment by viiliainen** [comment]
Hi,
I’ll start with finnish translations first.
When I have some spare time I’ll take a look how should it be done.
/Pekka

Lähettäjä: Rene Krenn ***@***.***>
Lähetetty: maanantai 4. huhtikuuta 2022 11.17
Vastaanottaja: phoenixctms/ctsms ***@***.***>
Kopio: Pekka Viiliäinen ***@***.***>; Mention ***@***.***>
Aihe: Re: [phoenixctms/ctsms] New Crowdin updates (PR #223)


@josharmenta<https://github.com/josharmenta> @viiliainen<https://github.com/viiliainen>
how to proceed now, you know who can help with your swedish/spanish translations?
it's giant, there are tens of thousands of strings.

we try to contact crowdin folks for advise on how to apply automatic translations for this initial commit. does it make sense?

**Comment by josharmenta** [comment]
Rene,

When I’ve used it in the past it basically required a refactor job to get all the language strings into one YAML or XML file, then those would be referenced from the main code.

**Comment by rkrenn** [comment]
@viiliainen 
ok. finalized now the exclusion filters in crowdin, so it no longer includes .properties files that are not language-related.

@josharmenta 
crowdin generates scaffolds for required/missing language files or folders (here in java we have .properties files, and in perl we have MakeText .po files). the crowdin UI is exposed via https://crowdin.com/translate/phoenix-ctms . i tried to add Spanish translations and it managed to complete 80%, but still requires the remaining to commit manaully. the changes in crowdin are then snchronized to the github pullrequest, which we can merge once it's 100%.

**Comment by rkrenn** [comment]
@CodeRabbit review

**Pull request closed without merging**
