### PR TITLE
[DO NOT MERGE] Maven Update

### PR DESCRIPTION
**Pull request by laborg**
Just as a basis for discussion. 
 - With this it is possible to use eclipse and the built in possibilities without the deprecated http://maven.apache.org/plugins/maven-eclipse-plugin/  
 - The build files in the repo do not contain any platform or user specific paths anymore (requires JAVA_HOME to be set to a jdk)
 - The repository doesn't contain IDE specific parts anymore
 - Adds a couple of clean ups (removed dependencies that aren't used anymore)

Open questions:
 - Is this really creating a usable war? 
 - Is the antrun copy task actually necessary?
 - Can the ant based builds be removed? Have they been superseeded by the maven plugin?
 - Can the build setup without maven-eclipse-plugin be used also on windows?

If we can decide on the utility of this change it would be a starting point to cleanup all pom files:
 - remove duplicated dependency entries
 - review dependencies
 - remove comments and apply automatic format
 - figure out dependency relationship between super-pom and child-poms.

### CODE REVIEW

**Comment by rkrenn** [comment]
>The repository doesn't contain IDE specific parts anymore
how to provide a ide setup then, instructions what jars's etc. to set?
to get rid of maven-eclipse, a working config for it's replacement would be needed.

the safe changes such as removing comments and disbale staging should be put into separate PRs.

**Comment by laborg** [comment]
Comments haven't been removed yet and I tried to make this a minimal set of changes to demonstrate the approach. If it's decided to stay on the same maven-eclipse-plugin usage I would do the safe cleanup in a different PR.

**Comment by rkrenn** [comment]
iirc no one is in love with maven-eclipse-plugin, so a PR for a working alternative would be appreciated ofc.
but no doubt it will be a hard task to migrate to an alternative.

**Comment by laborg** [comment]
Just to clarify: I wouldn't try to migrate to an alternative build process (e.g. gradle) but just to get rid of the deprecated maven eclipse interaction (maven creates eclipse) and switch to the eclipse native maven tools (https://www.eclipse.org/m2e/). Development on Eclipse works on Linux so far without need to adjust build path etc, but I need to test it further and do regression tests on the built artifact.

**Pull request closed without merging**
